// <auto-generated />
using System;
using MerchantCashFlow.Auth.Application.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MerchantCashFlow.Auth.Application.Persistence.Migrations
{
    [DbContext(typeof(DbCashFlowAuthContext))]
    partial class DbCashFlowAuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MerchantCashFlow.Auth.Application.Entities.Merchant", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope");

                    b.HasKey("MerchantId")
                        .HasName("pk_merchant_id");

                    b.ToTable("merchant", (string)null);
                });

            modelBuilder.Entity("MerchantCashFlow.Auth.Application.Entities.Merchant", b =>
                {
                    b.OwnsOne("MerchantCashFlow.Infrastructure.DataProtection.ProtectedValue", "AccountNumber", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid")
                                .HasColumnName("merchant_id");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(44)
                                .HasColumnType("character varying(44)")
                                .HasColumnName("account_number_hash");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("account_number");

                            b1.HasKey("MerchantId");

                            b1.HasIndex("Hash")
                                .IsUnique()
                                .HasDatabaseName("ux_merchant_account_number_hash");

                            b1.ToTable("merchant");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId")
                                .HasConstraintName("fk_merchant_merchant_merchant_id");
                        });

                    b.OwnsOne("MerchantCashFlow.Infrastructure.DataProtection.ProtectedValue", "Document", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid")
                                .HasColumnName("merchant_id");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(44)
                                .HasColumnType("character varying(44)")
                                .HasColumnName("document_hash");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("document");

                            b1.HasKey("MerchantId");

                            b1.HasIndex("Hash")
                                .IsUnique()
                                .HasDatabaseName("ux_merchant_document_hash");

                            b1.ToTable("merchant");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId")
                                .HasConstraintName("fk_merchant_merchant_merchant_id");
                        });

                    b.Navigation("AccountNumber")
                        .IsRequired();

                    b.Navigation("Document")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
