// <auto-generated />
using System;
using MerchantCashFlow.Statement.Application.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MerchantCashFlow.Statement.Application.Persistence.Migrations
{
    [DbContext(typeof(DbCashFlowStatementContext))]
    partial class DbCashFlowStatementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MerchantCashFlow.Statement.Application.Entities.DailyStatement", b =>
                {
                    b.Property<string>("DocumentHash")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("document_hash");

                    b.Property<string>("AccountNumberHash")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("account_number_hash");

                    b.Property<DateOnly>("StatementDate")
                        .HasColumnType("date")
                        .HasColumnName("statement_date");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasColumnName("balance")
                        .HasComputedColumnSql("credit - debit", true);

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("debit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DocumentHash", "AccountNumberHash", "StatementDate")
                        .HasName("pk_statement_daily");

                    b.ToTable("statement_daily", (string)null);
                });

            modelBuilder.Entity("MerchantCashFlow.Statement.Application.Entities.StatementInbox", b =>
                {
                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("LedgerId")
                        .HasName("pk_statement_inbox_ledger_id");

                    b.ToTable("statement_inbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
